// version.js — the game's version and what each update brought. Shown on the
// main menu (badge + "What's new"), in the pause menu, and automatically once
// after an update.
'use strict';
(function (G) {
  G.VERSION = '5.8.1';
  G.CHANGELOG = [
    {
      v: '5.8.1', name: 'Shift Lights', items: [
        ['🕹', 'Manual means manual', 'The Sting and the Stormer never change gear by themselves any more. Sit on the rev limiter and you stay on it until you shift up; a downshift goes in the moment you ask for it, and over-revving one costs the engine. The shift lights and a SHIFT ▲ call on the dial tell you when. A perfect shift on the blue light kicks harder than before, and the shop\'s acceleration numbers for both cars are measured shifting on the light. Everyone reloads the page (Ctrl+Shift+R) for this version, host first.'],
        ['⚠', 'Warnings off the road', 'Oil, mud, aquaplaning, crossings, falling concrete, the launch, the tide, crosswinds, rain, a rival and WRONG WAY used to be big red letters across the road ahead - and the crossings flickered. They are a small strip at the top now, under the pit strip and above the slipstream badge, where they do not cover anything. The pit call is a small strip too, with no banner: the sound, the flashing fuel gauge and the beacon over the box still tell you when to come in.'],
        ['⚖', 'Hard cars can win', '5.8 trimmed the Rotor for being the fastest car in expert hands. A car that hard to drive is allowed to be the best, so it is back: the quickest thing in the paddock if you can keep it on the boil, and the hardest for a beginner. The Stormer is the second quickest for experts; the easy cars, the Brick and the Dune, are still the ones to learn on.'],
      ],
    },
    {
      v: '5.8', name: 'Shift Lights', items: [
        ['🧱', 'Walls cost you now', 'Bouncing off the walls was quicker than driving: a glancing hit kept nearly all your speed and turned the car for free, which is also why people could beat even Legend bots. Now a barrier has real friction, scraping along one drags you down, and a proper hit knocks the drive out for a moment. Riding the walls round a lap is now about 8% slower than driving it clean. Everyone reloads the page (Ctrl+Shift+R) for this version, host first.'],
        ['⚙', 'Every car its own gearbox', 'Every car had the same five-speed, so once the gearing had scaled them a 9,000 rpm rotary and a 6,300 rpm V8 drove alike. Now the Mule has a long-legged four-speed, the Regent an eight-speed automatic that keeps pulling through its shifts, the Apex a seven-speed dual-clutch that shifts in a blink, the Brick a close six-speed rally box, the Dune a four-speed automatic, the Rotor a close five-speed and the Pip a five-speed for its tiny 9,000 rpm engine. Each engine makes its torque where it should - the V8 low down, the rotary near the top. The gearing parts reshape the car\'s own box, and every car card says which box it has.'],
        ['🕹', 'Manual gearbox: Sting and Stormer', 'These two you shift yourself: E up and Q down (change them in Settings → Controls), B or the d-pad on a gamepad, the ▲ ▼ buttons on a touch screen. Shift when the shift lights turn blue for a perfect shift - quicker than any automatic, with a shove as the gear bites. A downshift that would over-rev waits until the revs allow it. Leave the box alone and it only shifts after bouncing off the rev limiter, which is slow: a higher ceiling for the ones who learn it. Both wear a MANUAL tag, and bots shift them too - a Legend right on the light, a Rookie early or late.'],
        ['🎛', 'New gauges', 'A proper rev counter: numbered in the car\'s own rpm with its red line, a needle, the gear big in the middle and your speed under it. Shift lights across the top go green, amber, red, then blue when it\'s time to shift. Nitrous is an arc round the dial, and turbo cars keep their boost dial beside it.'],
        ['🅿', 'Pit stops you can\'t miss', 'The pit panel - fuel left, BOX THIS LAP - never actually appeared. It does now. When it\'s time to come in you get a banner and a sound, the fuel gauge flashes, the panel counts down the distance and says which side, and a beacon stands over the box. On the apron it tells you whether the box is ahead or behind and says STOP HERE when you\'re in it. The box is easier to stop in (anywhere alongside it, a little past either end), and backing up to a box you overshot no longer resets your car.'],
        ['💬', 'Who\'s typing, who\'s away', 'Room chat shows who is typing. The lobby, the grid and the standings mark AWAY anyone whose game is in the background or hasn\'t been touched for a minute.'],
        ['🚦', 'Revs on the grid', 'Bots blip their throttles while they wait for the lights, and a few hold it on the limiter for the last moments.'],
        ['⚖', 'Balance', 'Legend bots trust the racing line more: quicker, and fewer hits. The Rotor was the fastest car in expert hands on most tracks; with its engine now peakier it is still near the top, but no longer out of reach. The rest moved a little with their new gearboxes - none changed character. Scrapyard Gauntlet\'s barrel stack just after the hairpin is 12 m further on: bots hit it five times a race, and so did everyone else.'],
        ['⚡', 'Runs smoother', 'Night tracks and anything that glows made the renderer re-choose its shaders twice a frame: fixed, which cuts the game\'s own work per frame by about a sixth on Harrow City. Other cars\' engine sounds update 30 times a second instead of every frame, the minimap redraws at 30 fps, and the new gauges are drawn from a cached face.'],
      ],
    },
    {
      v: '5.7', name: 'Liftoff', items: [
        ['🗺', 'Three new tracks', 'Launch Coast: a spaceport by the sea at golden hour. The rocket on the pad lifts off every minute - smoke rolls across the infield, the ground shakes, and its blast shoves you across the coast road beside it. Countdown clocks by the road say when. Server Farm: a data centre at night, aisles of racks winking in the dark. Delivery robots cross from their docks, and fans in the walls blow gusts across the road. Low Tide: from a fishing village across a causeway to a lighthouse island as the evening tide comes in. Every few seconds a wave washes over the road - time it, or aquaplane. Everyone reloads the page (Ctrl+Shift+R) for this version, host first.'],
        ['🏎', 'Every car its own shape', 'From the chase camera most cars read as the same box with dark windows. Now each has a shape and a signature you can pick out at a glance: the Pip a white roof and a roof rack, the Brick box flares and a spoiler on its tailgate, the Sting speedster humps behind the seats, the Rotor louvres over the back window, the Vandal an 80s notchback with black bumpers and a ducktail, the Volt a sharp electric wedge, the Mule a shaker scoop and chrome bumpers, the Regent a black roof and a louvred bonnet, the Apex flying buttresses over the engine. Round, quad and slim headlamps too. How they drive has not changed.'],
        ['💥', 'Things to smash', 'Boxes, packs of loo roll, shopping carts, giant teddy bears, beach balls, lamps, cones, bins, tyres, hay bales and pumpkins, left on every track. Hit them and they go flying, tumble and stay where they land until the next race. They are only for show: they never slow you down.'],
        ['⚠', 'More on last update\'s tracks', 'Megastore: five forklift crossings instead of two, and a ride-on floor scrubber working back and forth across the wet patch. Harrow City: concrete now falls on four streets, not one. Harvest Run: pumpkins spilled by the farm stand and bales off the hay wagon. Puddles look like puddles instead of blue gems.'],
        ['🎵', 'Three new songs', 'Liftoff (city pop) for Launch Coast, Uptime (dark and pulsing) for the Server Farm and Low Tide (bossa by the sea). Settings → Music plays any of them.'],
      ],
    },
    {
      v: '5.6.1', name: 'Open Late, Harvest Time', items: [
        ['🗺', 'Harvest Run rebuilt', 'The valley sprint had the same five houses on repeat and golden dirt everywhere - it looked like a desert. Now every house is built on its own (size, storeys, roof, colours, garage, porch, chimney, solar panels) on streets full of trees, with side streets, a back street, parks, a church, a strip mall and a gas station. Downtown has shop fronts with awnings, signs and cafe tables, and buildings behind them. The valley floor is green with golden oak hills around it, and the farmland is vineyards, corn, row crops, orchards, a tree nursery and greenhouses behind eucalyptus windbreaks. The fields no longer cut into the road, and the towns have made-up names.'],
        ['⚠', 'Something new on each new track', 'Megastore: forklifts come out of the stockrooms and carry pallets across the aisle on two of the straights - amber lights flash when one is coming. Harrow City: concrete falls off the buildings on the east street, near the kerbs; a shadow on the road shows where each piece is about to land. Harvest Run: a tractor pulling two hay wagons crosses the highway between the barns. The HUD warns you as you come up on each one, and the bots know about them too.'],
        ['🛞', 'Oil, mud and water that bite', 'They used to matter only while a wheel was on them - a quarter of a second at speed - so you could drive through oil and feel nothing. Now oil stays on the tyres for a moment: grip and brakes fade as it wears off, and catching it with one side snaps the car round. Mud clogs the tread and drags. Standing water makes the front tyres aquaplane at speed, so the car ploughs straight on. The HUD says which one you hit, and the bots steer round them or lift. Everyone reloads the page (Ctrl+Shift+R) for this version, host first.'],
      ],
    },
    {
      v: '5.6', name: 'Open Late', items: [
        ['🗺', 'Three new tracks', 'Megastore: race through an endless furniture store after closing time - square corners between the showrooms, pillars that vanish into the fog where the ceiling should be, price signs on wires, and a freshly mopped floor. Harrow City: a city that emptied overnight - rain, fires, abandoned police cars and fire engines, barricades, neon, and the elevated railway still running over the start. Harvest Run: a sprint up a farm valley, from little downtown Clovehaven (say hello to the giant garlic) through the neighbourhoods, along the old highway past the vineyards and fields (mind the afternoon crosswind), and into downtown Oak Valley under the peak.'],
        ['🎵', 'Ten new songs and a music player', 'Four new garage songs - Showroom (bossa nova), Night Shift (lo-fi), Spare Parts (smooth funk) and Closing Time (slow and dreamy) - and the garage plays a different one each visit. Each new track has its own song, there are two new race songs (Sunset Drive, city pop; Night Line, drum and bass) so most tracks have a song of their own, and the menu now takes turns with a lounge tune. Settings → Music (or Esc → Music) lists all 18: press play to hear any of them, or keep one for the garage. Every note is played live by the game - there are no recordings.'],
        ['🔊', 'Turbo flutter you can hear in a race', 'The blow-off valve, the crackle, burble and bangs when you lift almost never went off in a race. They waited for the throttle to snap shut inside a single frame, and only the garage’s Listen button ever did that - so Listen and a real race sounded different. Now every proper lift in a race sets them off. And the flutter is the real stu-tu-tu-tu: bursts of air about 20 a second, slowing to 10 as the pressure runs out (a big turbo lower and slower). Recirculated is a soft whoosh on every turbo now; a big turbo used to flutter on it too, so picking Flutter changed nothing.'],
        ['🤖', 'Bots with more personality', '140 bot names. A bot’s car sounds like the way it drives - power and drag drivers like bangs, a lopey idle and a turbo flutter; grip drivers keep it tidy. Each one has its own habits too: a touch later or earlier on the brakes, neater or looser lines, more or fewer mistakes. Every difficulty level is as fast as before; it just isn’t eight copies of one driver any more. Hover a bot in the lobby to see how it drives.'],
        ['📈', 'Catch-up, any amount', 'Off, Mild (10%) and Wild (25%) are still there, or type any number from 0 to 100 - in the lobby for the host, and on the menu for quick races.'],
        ['🌐', 'One Play online button', 'Host and Join are gone from the menu: Play online opens the server list, which does both (Host a room and Join with a code are at the bottom). The online button in the corner now shows up by itself and counts the other people online - 0 when it’s just you. This version can’t play with older ones: everyone reloads the page (Ctrl+Shift+R), host first.'],
        ['🎨', 'Icons instead of emoji', 'Menus, the garage, the lobby and Settings use drawn icons now. Emoji look different on every computer and some Chromebooks show them as boxes; the icons look the same everywhere and match the game.'],
      ],
    },
    {
      v: '5.5.6', name: 'Lights Out', items: [
        ['🚦', 'No more freezes between races', 'The next race’s track used to be built all at once as the race started - up to a second and a half of frozen screen on a Chromebook, right on the grid - and the garage and the background race built a track of their own every round too. Now the next track is built a little at a time while you are in the garage, the betting board’s background race runs on it, and the race starts on it with nothing left to build; the garage’s test track is built once and kept. On a slowed-down test laptop, from the second round on, the start of a race, opening the garage and leaving it each take a hundredth of a second instead of up to a second and a half. In a room, the start lights are no longer hidden behind the race name at the top of the screen, and a sprint no longer says LAP SPRINT over lap times it can’t have.'],
        ['📶', 'Half the network traffic', 'A full room kept school Wi-Fi busy: every player got every car’s position 30 times a second, and the whole room - 20 KB and more - every time anything changed. Positions now travel packed into well under half the space (exactly the same numbers), cars a long way from yours come a little less often, and the room only sends what changed. Over a whole test session the host sent less than half as much as before. Everyone needs this version to play together: reload the page (Ctrl+Shift+R). If it’s the host who hasn’t, the game now says so instead of telling you to reload again.'],
        ['🔊', 'Sound tuning you can actually hear', 'The blow-off valve never made a sound at all (it waited for something that never happens), and most of the other choices sounded almost the same. Now a recirculated valve whooshes softly, an atmospheric one goes tsh and hisses loudly, and flutter goes stu-tu-tu-tu. Deep closes the note down to a big bassy boom, Raspy makes it hard and tinny, Straight-through is louder all round. Crackle is a fast dry crackling like a fire catching, Burble a low gurgle that lasts, Bangs the big ones, and Quiet calms the overrun. A lopey cam idles lump-lump-lump, a hard limiter stutters on and off while a soft one just wavers, and every pop and bang is voiced by its engine: a V8’s are deep thuds, a small four’s sharp cracks.'],
        ['⚖', 'Sting and Brick rebalanced', 'The Sting nearly matched the Mule V8 in a straight line and beat it off the line - not what a little roadster that loses out on straights should do. It now has less power (105 kW), a slightly lower top speed and an engine that wants to be kept revving: a quarter mile takes 15.6 seconds instead of 15.1 (the Mule does 14.9). It still changes direction like nothing else and still wins the tight tarmac tracks. The Brick, fully built, was the best car in the game on every kind of track while also being the easiest to drive; it now has a little less grip on dry tarmac (it pushes wide, as the description always said), and it is still the car for rain and dirt.'],
        ['🪨', 'Hazards back on the road', 'Serpent Pass’s last rockfall dropped every rock beside the road, most of them into the wall, and the ice on Frostbite Lake and the ford in the Freight Yard sat off to one side. All three are back on the road where they belong.'],
        ['🔒', 'Your seat is yours', 'The player next in line to take over as host used to be sent everyone’s secret rejoin code, so the room could carry on if the host left - and anyone in that spot could have used another player’s code to take their seat and their money. Now they get a one-way fingerprint of each code instead: enough to let the right person back into their own seat after a host change, useless for getting into anyone else’s.'],
        ['👋', 'A welcome for new players', 'Opening the game for the very first time now shows what it is, how a session works and the keys, instead of a list of fixes. Returning players still see what’s new after an update.'],
      ],
    },
    {
      v: '5.5.5', name: 'Stick Around', items: [
        ['🔌', 'The disconnect loop, found', 'Once a room had been going for a while - a full grid, a long chat - the room’s details no longer fitted in one message on a direct connection. The connection library refused to send them and hung up instead, so with every update each player on a direct link dropped out and rejoined, over and over. Players on the backup relay were fine, which is why it only ever hit some of you. Big messages now go in pieces and are put back together at the other end. The host needs this version for it to work: a player whose game is older is asked to reload, and if you and the host are on different versions the game tells you who should reload. And a game whose connection closed at the very moment it got back in no longer sits frozen on the old screen: it carries on trying.'],
        ['🔇', 'No more freezes from silent sound', 'With sound on but the browser’s audio not running yet (before your first click or key, or when the speakers or headphones went away), the game kept lining up engine, tyre and wind sounds that nobody could hear. Each one cost more than the last, so a few minutes into a race a Chromebook could freeze for seconds at a time and get dropped from the room. The game now waits until the audio is actually running.'],
        ['🔗', 'Steadier joining', 'A laptop that took a few seconds to connect could end up on one of two connections while the host used the other, so they talked past each other and it kept retrying; it now listens on both. Joining shows the room straight away instead of a flash of your own menu, keeping the next host ready takes less of the network, and if part of the game doesn’t download on a busy network you are told to reload instead of getting a broken page.'],
        ['🐢', 'Smoother on Chromebooks', 'The automatic graphics setting lowered itself for good at every loading pause and hardly ever came back, so by the end of a session the picture was at its blurriest; it now judges your real frame rate, climbs back when it can, and undoes a step that didn’t help. The scenery made the graphics card redo its setup on almost every draw, the game built a whole new background track after every race and when you joined a room, lamps and rain got their graphics ready only when they first appeared mid-race, and the sounds re-sent thousands of unchanged settings a second. A slowed-down test laptop now spends about 40% less time on each frame of a race.'],
        ['📶', 'Connection report', 'Esc → 📶 Connection shows how your link is doing: direct or through the backup relay, your ping, how many of the host’s updates are arriving, and every drop with its reason and how long it took to get back in. The host sees every player’s link. If you keep dropping out, press Copy debug info and paste it to whoever runs the room. It stays on your computer unless you paste it somewhere.'],
        ['🖥', 'Fits the screen', 'On a 1366×768 screen - most Chromebooks - the main menu no longer runs off the top and bottom (the controls line and the Drive button were off the screen), and the garage between races no longer tucks its tabs under the next-track map or puts the chat buttons over its notes. Betting only offers stakes the rules allow (bets $50-$400, side bets $100-$700), says why a bet button is off, and a side bet against a bot tells you how much it will take.'],
      ],
    },
    {
      v: '5.5.4', name: 'Stay Connected', items: [
        ['🔌', 'Dropped players get back in properly', 'When a player’s connection dropped mid-race, three things went wrong at once. Back in the room, their game started counting its controls from zero again while the host still remembered the old count, so the host threw every new input away and a stand-in drove their car for the rest of the race. While it reconnected, the screen swapped to the menu’s background race and back, building two whole tracks - a long freeze on a Chromebook, and on a weak connection long enough to drop out all over again: the disconnect-and-rejoin loop. And any stall over 6 seconds counted as a disconnect, although school Wi-Fi often recovers from those by itself. Now the race stays on screen while you get back in, your car answers to you the moment you’re back, and a connection gets 10 seconds to come back on its own before the game reconnects.'],
      ],
    },
    {
      v: '5.5.3', name: 'Who’s On', items: [
        ['👥', 'Online players and messages', 'The 👥 button in the top corner shows everyone playing SLIPSTAKES right now, anywhere, and what they’re doing: on the menu, in the garage, racing solo, or in a room. If their room is public you can join it straight from the list. The 💬 button sends them a direct message; new messages pop up wherever you are and the 👥 button counts the ones you haven’t read. Messages are end-to-end encrypted, so only the person you send them to can read them, and nobody can send one pretending to be someone else. They vanish when you close the game. You can hide yourself from the list or turn messages off right in the panel, and Block stops someone messaging you for the rest of the session.'],
        ['🔌', 'No more join-and-drop loops', 'The first player to join a room is next in line to host if the host leaves. When THEIR Wi-Fi dropped for a few seconds, the game decided the host had gone and made them host of a copy of the room, while the real host carried on. The room split in two, each half saw the other as disconnected, and in a two-player room the real host then moved into the copy - so every hiccup bounced the room back and forth and players kept dropping out and rejoining. Now a player who loses the host simply reconnects to the same room, and the next in line only takes over when the host really has gone (it said so, the room no longer exists, or nobody has reached it for 40 seconds). If a copy ever does get made, it notices the original is still running and moves back into it.'],
      ],
    },
    {
      v: '5.5.2', name: 'Steady', items: [
        ['🏎', 'Other cars stop wobbling', 'On a joiner’s screen, other cars - people’s especially - swayed from side to side in a way the real cars never did. Three causes, all fixed. Every car was guessed ahead from the moment each update ARRIVED, so on jittery Wi-Fi the point it was guessed to jumped back and forth by up to a metre with every update; it is now timed from the host’s own clock. A person on a keyboard changes their rate of turn several times a second, and carrying each one a third of a second ahead swung the drawn nose from side to side; the guessed turn now fades the way a real car’s does. And the smoothing that hides each correction slid cars sideways without turning them, a crab-walk that read as a wobble; it now takes sideways corrections gently. Measured against where the cars really were, a keyboard player’s side-to-side movement is 2 to 3 times smaller and their nose sways about as much as the real car’s does, with no return of the old stutter.'],
      ],
    },
    {
      v: '5.5.1', name: 'Say It Your Way', items: [
        ['🎤', 'Voice settings', 'Speech to text has its own tab in Settings, with four ways to use it. Push to talk: hold V and speak, and letting go sends it. Tap to talk: tap V or the microphone once, and it sends when you pause. Voice activated: it listens the whole time you are in a session and sends each sentence when you pause, and V or the microphone mutes it (the microphone button goes grey while muted and gets a green ring while listening). Or Off, which also removes the microphone buttons.'],
        ['🎚', 'Tune it to your room', 'Voice activation has a sensitivity slider, so a classroom behind you doesn’t end up in the chat, and it ignores lone “uh”s and mumbles the recogniser itself wasn’t sure of. Test your microphone right in the settings: a live level meter shows your voice against the point where voice activation starts listening, with what it heard underneath, and nothing is sent. You can also pick the language you speak, how long a pause ends a message, whether voice activation runs all session, in races only or everywhere but races, and how far the game turns down while you talk.'],
        ['✍', 'Check it before it goes', 'Choose “Put it in the chat box to check first” and your words land in the chat box instead of going straight out, so you can fix a misheard word and press Enter. Live captions, the 🎤 mark in front of spoken messages and the listening blips can each be switched off.'],
      ],
    },
    {
      v: '5.5', name: 'Clean Air', items: [
        ['🤖', 'Bots that keep it on the island', 'Measured over 45 Hard races on fifteen tracks, the bots now hit the walls less than half as often (264 times down to 115), need a reset less than half as often, and bump into each other 40% less, and they finish a little quicker for it. The main fault was their braking: the pedal came in late and soft, so they reached every corner a metre or two a second too fast and slid wide into the barrier. They brake a moment sooner and firmer now. A bot that feels itself running wide lifts, and remembers the corner, so next lap it arrives slower there. Nose-first against a wall or a fallen rock, it backs out and goes round instead of pushing until it gets reset. After the finish of a point-to-point race it stops short of the barrier at the end of the road instead of nosing into it.'],
        ['🤝', 'Room for people', 'Bots now know which cars people are driving and race them cleaner: a wider gap alongside, a longer look ahead and sooner off the throttle behind you, and they no longer move over to block a person trying to pass. Contact between the bots and a driver racing them cleanly fell by more than half in testing. A rival bot still goes looking for trouble, but it only goes after a person who rammed it first.'],
        ['📡', 'Smooth cars online', 'Every snapshot from the host froze every other car on a joiner’s screen for exactly one frame - 30 times a second - before it caught up: a fine, constant shimmer on every car you raced against, up to half a metre at speed. That is gone, and corrections now ease in and out instead of kinking the car’s path. Players on the backup relay see other cars 1.2 m from where they really are next to them instead of 2.9 m. A Wi-Fi stall of up to half a second no longer freezes the other cars and then jumps them up to 5 m forward when it clears, and your own car glides back into line after one instead of being yanked.'],
        ['🎤', 'Speech to text', 'In multiplayer, hold V or tap the microphone next to the chat and speak: what you said goes into the chat. It is for anyone who wants to talk but can’t use a headset. The game goes quiet while you talk, so laptop speakers don’t drown you out. It uses your browser’s own speech service (Chrome or Edge), which asks to use your microphone the first time, and it can be switched off or moved to another key in Settings → Controls.'],
        ['🔁', 'Quicker reconnects on school Wi-Fi', 'If the direct link to a room couldn’t be made, a reconnect now tries the backup relay straight away instead of spending eight seconds finding out again.'],
        ['🪟', 'Roofs in one piece', 'The metal roof on every car was a panel laid a few millimetres over a cabin made entirely of glass, and from any distance the two fought over the same pixels, so the glass flickered through the roof. It was worst on the fastbacks, where the sail panels behind the doors were laid on the same way. The cabin is now built as a single surface: glass where there is glass and metal where there is metal.'],
        ['🔋', 'The electric bot stops cooking itself', 'The bots managed an electric motor’s heat with the rule written for a turbo, so a bot in the Volt E with a motor upgrade spent two thirds of a race overheated and derated, and finished well back. It now eases off as the motor warms, never reaches the cut-out, and is 11 seconds quicker on the Grand Tour.'],
      ],
    },
    {
      v: '5.4', name: 'Level Crossing', items: [
        ['🏎', 'Two new cars', 'The Regent V12 is a long-bonnet grand tourer: the highest top speed in the paddock and dead steady flat out, but 1.6 tonnes arriving at every hairpin, and no use on dirt. It owns the fast tracks. The Rotor 7 is a light rotary coupé that revs to 9,000 and makes almost nothing below half of that: keep it spinning and it flies through flowing corners, drop it off the boil and it bogs. Both have their own engine note - a silky V12 scream and the rotary’s buzz, with a lumpy “brap” at idle - and both are premium cars you buy in a session.'],
        ['🗺', 'Three new tracks', 'Frostbite Lake: a winter circuit with a causeway straight across a frozen lake - 280 m of sheet ice with a kink in it and the wind coming off the water, tarmac everywhere else. Freight Yard: a dusk circuit that crosses the main line twice, and the trains run to a timetable. Ashfall Ridge: flat out down a live volcano, with a crosswind on the crater rim, two long runs on loose ash and lava bombs raining into the road.'],
        ['🚂', 'Level crossings', 'A train of nine wagons crosses the road on its own timetable. The lights flash as it comes, the barriers are open at the rails, and the HUD calls it from 170 m out because at chase-camera height you would see the lights too late. Beat it across or wait: it does not stop, and the side of a moving train is exactly as solid as it looks. The bots wait for it too.'],
        ['⛰', 'Serpent Pass fights back', 'Its rockfall gorge only ever held ONE rock at a time over 150 m, and it was the only rockfall on a point-to-point run - so you met it once, near the start, and that was it. The gorge now runs four streams of rocks, and two more rockfall zones come down on the descent, so the mountain keeps throwing things at you all the way to the finish. Bigger dust clouds when they land, too.'],
        ['🎨', 'A paint shop that makes sense, and new things in it', 'The Paint tab was fourteen sections in one long scroll, with the colour, its finish and the accent three screens apart and the whole Sound section in the middle. It is now four tabs - Paint, Body, Wheels and Sound - with your current choice beside every heading, and the camera drops low and close when you pick the Wheels tab. Dragging the car round no longer highlights every word it passes over. New in it: Heritage band, Contrast panels and Retro pinstripe liveries, Split 5 and Classic 8 wheels, and a Pearl finish.'],
        ['🔊', 'Every car sounds like yours', 'Other cars ran on a much cheaper voice than your own - three oscillators and a filter - and at 20 m played at about a sixth of your engine’s level. They now get the same recipe as yours: the combustion grit that makes an engine sound like an engine, their gearchanges and limiter, the supercharger’s full whine and the turbo’s whoosh, and you hear the nearest five from 150 m. And a supercharger’s whine is about 1.7 times louder, on your car and theirs.'],
        ['🔧', 'The next track in the garage', 'The layout of the next race is shown in the garage now, beside NEXT RACE, where you can still build and tune for it. On the start line it was too late to do anything about.'],
        ['🚦', 'Ten seconds on the grid', 'The countdown runs from ten instead of three, with the five start lights coming on one a second over the last five and all going out for the go. Enough time to see the start coming, pick your line into the first corner and rev the engine through it.'],
        ['⚖', 'The V8 wins the drag again, and the Volt stops winning everything', 'A wing made the same downforce in newtons on every car, so on a 960 kg roadster it was half again the grip it was on a 1,440 kg muscle car: the Full Aero Kit made the Sting S 8% faster and the Mule V8 2%, and a fully built Sting won more tracks than anything in the paddock. Aero is now sized to the car it is bolted to, so downforce per kilo comes out close to even. The Mule also had only 6% more power per kilo than the four-cylinder; it now has 190 kW and wins a quarter mile by three tenths. The Volt E was winning six tracks of seventeen whether stock or fully built, because a cooling upgrade cancelled the one thing meant to hold it back - its motor running hot on long runs. Cooling parts now do half as much on an electric motor, and it runs a little hotter. Its launches and its grip in the rain are untouched.'],
        ['🏎', 'An open cockpit you can see into', 'The roadster’s cockpit is cut into the body now, with the seats, dash and tunnel sitting down inside it, instead of a black tray laid on the deck with the furniture stood on top. Its windscreen has a real frame, and its mirrors are bolted to the doors — they used to start a few centimetres above the bodywork, in mid-air.'],
        ['🛠', 'Fixes', 'A bot pinned against a barrel stack only counted itself stuck while flat on the throttle, so one feathering it sat there for the rest of the race; it now asks for a reset (but not while it is waiting for a train on purpose). Mirrors on every car start inside the bodywork. The big bonnet scoop is sized to the bonnet it sits on - it ran into a small car’s windscreen. Roof stripes follow the roof instead of floating off the ends of a curved one, the widebody sill meets the body on a narrow car, and flank liveries stop short of the wheel flares. Car select fits eleven cars with every card’s stat bars showing. A sprint or a drag no longer shows a Best lap column of dashes in the results. On a phone the garage title no longer runs under your cash.'],
      ],
    },
    {
      v: '5.3.2', name: 'Clean Lines', items: [
        ['🧹', 'Nothing left hanging in the air', 'Every car was rebuilt as real geometry in a 3D package and measured piece against piece, which turned up a list of things floating a centimetre or two off the bodywork. The roof panel took its width from one cross-section, so on any cabin that narrows towards the back it overhung the glass by 10 cm and sat 5 cm above it — a plank laid across the roof. It follows the cabin’s own top line now, and the aerial that stood on that slab came down with it. Wipers took their height from the base of the windscreen and hung 2–3 cm in the air on every car whose cowl drops away from it; they lie on the scuttle. The pickup’s spare wheel floated 10 cm over its own bed, and the rally light bar was sitting inside the intercooler.'],
        ['🎨', 'Kit parts that stop fighting each other', 'The widebody kit drew its arch straight over the standard arch trim, and with wide tyres fitted over a second set of flares as well — three pieces cutting through one another over every wheel, with two sets of side skirts below them. The kit’s arch now replaces the lot, and its sill stops short of the arches instead of running into them. A diffuser fin standing exactly where a tail pipe comes out gets out of the way. Liveries sat as much as 3 cm off the paint, which is close enough to see; they are 5 to 11 mm now, still hundreds of times what it takes to keep them from flickering. The big aero splitter was a fixed 1.9 m plank — wider than some of the cars it was bolted to — and exhaust tips stood 16 cm proud of the bodywork.'],
        ['🌤', 'An open car with the roof properly down', 'The roadster’s cabin was lofted as a closed volume in tinted glass, which laid a dark lid over the cockpit and hid everything in it. Only the windscreen is glass now — leaning back from the scuttle to the top rail, on pillars you can see — and the seats, dash, deck and headrests hang off the screen instead of off fixed numbers, so they land in the right place whatever body they are in.'],
      ],
    },
    {
      v: '5.3.1', name: 'Overrun', items: [
        ['💨', 'Pops you can see, and that stop', 'A free-flowing exhaust now throws smoke out of the pipe on the overrun, and a bangs-and-pops map spits flame with it — visible whether or not your sound is on. The bang tune also had two faults: it fired exactly ONCE when you lifted (the test only looked at the instant the throttle shut, not at the overrun that followed) and then, once that was fixed, it never stopped. It now cracks hard as you lift and fades out over a couple of seconds, the way a real one does.'],
        ['🔧', 'Fixes', 'Wheel-arch trim is narrower, so it reads as trim rather than a slab bolted to the side. The open cockpit in the roadster — seats, floor, dash and roll hoops — is measured from the car it is in instead of fixed numbers, so nothing sinks through the deck.'],
      ],
    },
    {
      v: '5.3', name: 'Know Your Car II', items: [
        ['⚖', 'Top speed comes from the engine again', 'The final drive used to be set so every car hit its rev limiter exactly at its rated top speed. That made top speed a property of the GEARBOX and nothing else: a Big Turbo was worth literally 0 km/h, and longer gearing was the right answer on every track, which is why the final-drive slider never felt like a choice. Each car’s drag is now worked out from the speed its card claims, and top gear reaches about a tenth past it — so a standard car runs out of AIR, power buys 18 to 26 km/h, short gears cost you 14 to 32, and long gears unlock the rest only once you have the power to use it. Stock top speeds moved by less than 2%.'],
        ['⚙', 'Parts that do what they say', 'Every part on every car was measured against its own description. A kei car was being sold a Race Shell that was byte-for-byte the Carbon Panels it already had, because weight came off in flat kilos and a small car ran out of things to remove — weight is now a share of the car, scaled down for the little ones, and all four steps are real on all nine cars. The one factory-turbocharged car could not adjust its own boost, because the slider was looking at the wrong slot. An electric car was being sold a sequential gearbox for its single-speed transmission, a front-mount intercooler for an engine it does not have, and anti-lag; it is now sold none of them, and its motor packs raise its rev ceiling instead, which is the only way an EV goes faster.'],
        ['⛔', 'Brakes tell the truth', 'A brake card promising "+12% stopping power" could never deliver it: the tyre gives up before the pedal does, so every brake stopped in the same distance from cold. What they really buy is enormous and was never mentioned — road brakes go from 37 m to 49 m by the end of a race while carbon stays at 37 m. The cards now say that, and brake capacity was brought down enough that a car with sticky tyres and real downforce can genuinely run out of brake, which is the actual reason to fit bigger ones.'],
        ['💰', 'Betting is a side bet again', 'A 700 stake at the old 30x ceiling paid 21,000 against a 1,800 race win, and the surest way to it was backing YOURSELF: the book prices a driver off their car and recent results, so anyone quick in a modest car was priced as an outsider and knew it. Odds now top out at 9x (4.5x on yourself), stakes are smaller, and a best-case betting race is about 3,600. Late joiners also get a fair start: they used to be given 80% of the POOREST driver’s worth with parts valued at half, which left them unable to race anybody; now it is 85% of the middle of the field, with parts counted at what they would actually have to pay.'],
        ['🔌', 'The race-start disconnect is fixed', 'Building a track blocks a slow device for a few seconds, and both ends were reading that silence as a dead connection — so every race start risked a disconnect, a reconnect, another track build, and round again. Time spent with a frozen main thread no longer counts as silence, and a host waits 20 seconds for a slow machine instead of 10. Twenty-four seconds of deliberate freezing now survives without dropping.'],
        ['🔊', 'Sound you can tune', 'The exhaust now amplifies what the engine already IS, instead of the same multiplier on every car: a straight pipe on the V8 finds rumble, the same pipe on the three-cylinder finds rasp. And there is a Sound section in the garage — exhaust tone, what it does on the overrun (crackle, bangs and pops, a burble tune), the blow-off valve on a boosted car, a lopey idle and a hard-cut limiter. Free, cosmetic, and each one needs the hardware that would make it possible.'],
        ['🔥', 'Anti-lag bangs', 'It made flames and almost no noise, because it holds the backfire on for the whole overrun and the game only listened for the moment it started — a ten-second overrun got exactly one pop. It now cracks away for as long as it is lit, on your car and on the ones going past. Exhaust flames and shift puffs also come out of the pipes you actually fitted: side exits used to breathe fire out of a rear bumper with no pipes in it.'],
        ['🎥', 'Rev it, and a lower camera', 'Holding the throttle on the grid pegged the engine at a fixed 69% of the redline instantly and held it there. Now it winds up against its own inertia, drops back when you lift, and bounces off the limiter if you hold it — and a small engine spins up faster than a big one. There is also a Low chase camera, down near the road where you can see into the corner, and the TV cameras now work while you sit a race out or watch the betting board.'],
        ['🗺', 'See the circuit first', 'The pre-race screen draws the next track: the layout, which way round it goes, where the start line is, which parts are loose or under water, and where the pit lane is if it has one.'],
        ['🤖', 'Bots leave room', 'They could see cars in front and cars behind, but nothing ALONGSIDE, so two of them running wheel to wheel both kept pulling to the same racing line and leaned on each other the whole way down the straight. They now leave each other as much room as the road can give. Over forty races that is a sixth fewer contacts and three quarters fewer spins — and slightly quicker laps.'],
        ['🔧', 'Fixes', 'Spoilers sat on a number measured elsewhere on the car, so a ducktail or whale tail floated 43 cm above a hatchback and 58 cm above the kei car; they now sit on the bodywork, at the trailing edge of the roof where a hatchback wears one, and take their width from the car rather than a constant. The widebody kit was two plain boxes beside each wheel and is now an arch that follows the wheel and blends into the body, with a sill joining the front and rear. The Sting S was quietly the strongest car in the game once fully built, and the electric car the strongest out of the box; both are back in line.'],
      ],
    },
    {
      v: '5.2', name: 'Same Road', items: [
        ['🛰', 'Everyone is on the same road now', 'If you were the one who JOINED a room, every other car on your screen was in the past. Your own car is drawn where it will be once the host has heard from you, but the other cars could only be drawn where the host said they were a round trip ago — and then they were held back another tenth of a second on top of that, to keep them moving smoothly. Measured end to end, a car sat 2.7 m out of place on a home network, 3.6 m on Wi-Fi and 8.9 m through the backup relay — against a car 4.3 m long. That is why you could be shoved by a car that was not next to you yet, why hitting somebody back felt like driving through them, and why the whole thing looked out of sync. Every other car is now carried forward onto your own clock instead, following how fast each one is turning rather than just where it was pointing, so a car in a corner stays in the corner. The same measurement now reads 1.1 m, 1.5 m and 3.1 m. Nothing about the racing changed — the host still decides everything — you are simply being shown it on time.'],
        ['💥', 'Contact happens when you see it', 'A joiner used to slide into somebody, keep going, and then get snatched back when the host’s version of the crash finally arrived. Your own half of a bang is now worked out on your own machine as it happens, using the host’s collision maths, so you stop against the car you can actually see and the bang and the sparks land at the moment of contact. The host still has the final say and still settles who pushed whom. On a link too slow to be sure where the other cars are — the backup relay — this stays off rather than invent a crash that never happened.'],
        ['📶', 'Thirty updates a second, and a link you can read', 'The host sends the race out half again as often as it used to (a relayed room stays lower, because the public relay limits how much it will carry). And when your connection really is the problem, the HUD now says so — RELAY or SLOW LINK, with the ping — instead of leaving you to wonder why the cars feel wrong.'],
        ['🔧', 'Fixes', 'One unusually quick packet used to skew a joiner’s idea of the host clock for about five seconds, and every car on screen stuttered until it bled off; that estimate now uses a moving window. Cars are also no longer carried through a barrier while the game is working out where they went.'],
      ],
    },
    {
      v: '5.1', name: 'Know Your Car', items: [
        ['⚖', 'Every car is somebody', 'A full balance pass with one rule throughout: no car is made average. Each one is quickest somewhere and beaten somewhere else, and they are deliberately not equally easy — the Brick R and the Dune Runner are forgiving cars with a lower ceiling, the Apex MR and the Sting S ask for real skill and pay for it, and the rest sit between. Stripping weight is now capped at about a quarter of a car’s own weight, so a tiny car can no longer be turned into a 400 kg go-kart that beats everything.'],
        ['🏎', 'Muscle, roadster, hatch, truck', 'The Mule V8 has a real V8 torque curve and the top speed to go with it: nothing beats it away from a slow corner or down a long straight, and it still cannot change direction. The Sting S turns in quicker than anything else in the paddock and owns the tightest circuits. The Brick R is the car you want when the rain starts. The Dune Runner is more truck than ever — better on the loose, worse on tarmac.'],
        ['🌀', 'The Stormer keeps its own turbo', 'The Group B car no longer takes shop turbos, because bolting a bigger one on just made it the same car with more power. It has a Rally Turbo slot of its own instead: the Factory turbo, a Small Rally Turbo that spools in half a second and makes it driveable on tarmac at the cost of the top end, or a Group B Turbo with a second and a half of lag and everything at once. That is a choice about how hard you want the car to be, not a straight upgrade.'],
        ['🔋', 'A motor for the Volt', 'The electric car has a Motor and Inverter slot: a Sport Inverter or a Race Motor Pack, each one faster and each one hotter. Its motor now fades smoothly as it heats instead of doing nothing and then cutting to half power, so a long flat-out run asks you to lift early and let the brakes charge it back up.'],
        ['💰', 'Money that makes you choose', 'A race used to pay roughly what the best part in a slot costs, so everyone bought the best thing the moment they wanted it and the cheap half of the catalogue was never touched. Purses are about a third smaller, you start with less, and the big parts cost more — while sport pads, a cat-back, narrow tyres and an alloy radiator are all the price they always were. The first races are now spent on those, and a Race Shell is something you work towards. Running costs bite too: a fully built car costs more per race in fuel and wear than a mid-pack finish pays.'],
        ['⛽', 'Endurance can turn up anywhere with a pit lane', 'Endurance Park is still always the endurance race, but Harbour Loop, Dustbowl Oval, Rainline Hairpins and Grand Tour have their pit lanes back, and each one has a chance of being run as an endurance race — a long race with fuel, tyre wear and a stop. A session gets at most one surprise, and the schedule tells you which race it is before you build the car.'],
        ['🎛', 'A smaller, sharper instrument cluster', 'A proper rev counter whose shift lights ring the dial instead of taking a row above it, a bigger speed readout and gear beside it, and a boost gauge of its own instead of a seven-pixel bar — with a mark showing what the turbo could be giving you at these revs, so you can see the lag you are waiting out. An electric car gets a motor temperature dial in the same place, with the derate zone in red. The whole panel is a third shorter than it was, so there is more road to look at.'],
        ['💨', 'You can see the crosswind', 'The gusty stretches used to shove you sideways with nothing on screen to say why. Now grit blows across the road, wind socks line the whole zone, and the HUD says CROSSWIND and which way it is pushing.'],
        ['🎵', 'Music you can actually hear', 'The menu, garage and results themes were the last music left from v4. They are rewritten on eight-bar progressions with the sections, echo and pump the race songs use, and street circuits get a song of their own. The music was also mixed too quietly to hear under the engines, so it is louder by default.'],
        ['🔧', 'Fixes', 'The pit lane no longer flickers: the box, its white lines and the PIT stripe each sit at their own height instead of fighting over one. The shop shows the real weight saving for the car you are in, not a number from a different one. Bots have stopped buying parts their car cannot use.'],
      ],
    },
    {
      v: '5.0.2', name: 'Fits the screen', items: [
        ['⛽', 'Endurance lives on its own track', 'Endurance is no longer a session mode you pick. Endurance Park simply IS the endurance race: whenever it comes up in a session or a quick race, it is a three-lap run where fuel and tyres wear out and you stop in the pits. Harbour Loop, Dustbowl Oval and Grand Tour are back to normal races.'],
        ['🖥', 'A lobby that fits', 'The host lobby is three panels now — drivers, settings and chat — each scrolling on its own. A full grid of eight drivers can no longer push the settings or the Start button off the bottom of the screen.'],
        ['🌐', 'Roomier server list', 'More space inside the panel and inside every room row, so no text sits against an edge. The old Endurance filter is now "Racing now".'],
      ],
    },
    {
      v: '5.0.1', name: 'After Dark hotfix', items: [
        ['🔋', 'Volt garage fix', 'Choosing the Volt E in the garage no longer turns the screen white.'],
        ['🔊', 'Every car sounds like itself', 'Other drivers\' cars now have their own engine voices too: the Mule burbles, the Pip buzzes, the Stormer warbles and the Volt whines past, instead of every car sounding alike with only the pitch changed.'],
      ],
    },
    {
      v: '5.0', name: 'After Dark', items: [
        ['⛽', 'Endurance racing', 'Endurance Park is the endurance race: a longer run where fuel and tyres wear out, so you stop in the pit box and work your crew — choose tyres and fuel, hold to fill and let go on the line, then hit the wheel gun in the green. Your HUD tells you when to box. Bots pit too.'],
        ['🗺', 'Four new tracks', 'Serpent Pass, a true two-minute mountain sprint. Grand Tour, one long lap as evening falls. Neon Nights, downtown after dark. Endurance Park, a parkland circuit with a pit lane where the sun sets as you race.'],
        ['🌙', 'Night and weather', 'Street lamps, neon signs and headlights light the way at night. On Changeable weather a shower can start mid-race and the road turns slippery: narrow tyres and rain tyres cope best. Set the weather in the lobby or next to Quick race.'],
        ['⚠', 'New hazards', 'Falling rocks in a mountain gorge (watch for the shadow), swinging wrecking balls, gusty crosswinds, water splashes that grab your wheels, and a gravel trap you can cut across if you dare.'],
        ['🚗', 'Three new cars', 'Pip K1: a free kei car, slow on paper but light, nimble and thrifty with fuel. Volt E: electric all-wheel drive with instant torque; it gets hot on long straights and recharges under braking in endurance. Stormer B: a Group B rally legend, untouchable on loose surfaces and a handful on tarmac. Every car has a track where it shines, and some need real skill to get there.'],
        ['🤖', 'Smarter bots', 'Six difficulty levels, Rookie to Legend, for quick races and hosted rooms (the host picks). Bots take racing lines, pass on the inside, defend and sometimes make mistakes. Now and then one turns rival and goes looking for someone to bump, bot or player, and you get a warning if it\'s you.'],
        ['🔧', 'New parts and looks', 'Rain tyres, an intercooler, launch control or anti-lag, magnesium wheels, and a pit kit (a bigger fuel cell or quick-release wheels). In Paint: body kits, spoilers, exhaust tips, three new liveries and pulsing or rainbow underglow.'],
        ['🏆', 'Championships, horn and TV cameras', 'Hosts can decide the winner by championship points (25-18-15-12-10-8-6-4, +1 for the fastest lap) instead of money. Press H to honk. Press C for TV cameras that cut between trackside angles.'],
        ['🔊', 'Sound and music', 'Tyre roar and tread hiss that grow with speed, crunching gravel, splashes, breaking glass in big crashes, and sounds of each place: birds, sea, city, rain and thunder, crickets at night. Pit crews rattle their wheel guns. New race music for day, night, rally and endurance builds on the final lap, and is on by default.'],
        ['🌐', 'A cleaner server list', 'Filters, search and each room\'s status, mode and next track at a glance, and the list no longer blinks while it updates. Lobby settings are grouped and easier to read.'],
        ['🔧', 'Fixes', 'The ground no longer cuts into the road on mountain tracks. A premium car bought with sandbox money no longer carries into a hosted room.'],
      ],
    },
    {
      v: '4.5', name: 'Sound & Scale', items: [
        ['🖥', 'Fits every screen', 'The whole interface is laid out for a Chromebook screen and scales to yours: no more cut-off menus in small windows, and a HUD that isn\'t tiny on a big monitor. The minimap and speedo stay sharp at any size. New Menu size setting next to HUD size (now 70–130%).'],
        ['🔊', 'Engines with grit', 'Every engine has combustion rasp pulsed at its firing rate and an exhaust that rings at its own pitch, and idles wander like real ones. Turbos whistle with a blade overtone and sing loudest while they spool; superchargers whine locked to the crank with a rotor whirr, and hiss through the bypass valve when you lift.'],
        ['🔔', 'Sounds for the room', 'A knock and a bell when someone asks to join your private room, chimes when drivers join or leave, a fanfare for a new host, and a warning before an idle room closes. Info pop-ups blip softly.'],
        ['👋', 'Left or lost?', 'The chat now says whether a driver left the game or lost their connection (their seat is saved either way).'],
        ['📡', 'Lighter netcode', 'Snapshots are smaller (your own car\'s part is less than half the size), and a weak Wi-Fi link now skips stale packets instead of queueing them up as lag. The race loop and car sounds also create less throwaway data every frame.'],
      ],
    },
    {
      v: '4.4.2', name: 'Smooth Tow', items: [
        ['⚡', 'Smoother in a pack', 'Racing in a pack of 7 cars costs far less frame rate: name tags only update when they move, glows from distant cars are skipped, and crash sparks, thuds and exhaust crackles are capped, so a pile-up can\'t flood the screen and speakers.'],
        ['🌬', 'Slipstream you can see', 'Catch a tow and a SLIPSTREAM badge lights up at the top of the screen with how much drag you\'re saving, the screen edges glow blue, and a whoosh tells you you\'re in. The badge glows brighter at full tow: time to pull out and pass.'],
        ['⚓', 'Harbour boats', 'A boat could sit on the track at Harbour Loop. The boats are back out on the water.'],
        ['🔇', 'Stuck sound fixed', 'After a race next to a bot with a supercharger or turbo, its whine could keep playing on the main menu. It now stops with every other car sound.'],
      ],
    },
    {
      v: '4.4', name: 'Crowd Control', items: [
        ['👀', 'Spectate after the flag', 'Once you finish, the camera moves to the cars still racing: 1–8 or Tab picks one, F goes back to your own car, WASD flies a free camera.'],
        ['🤖', 'Livelier bots', '40 names (never two alike), random paint, finishes, liveries, rims and lights. Each bot has a style (grip, power, rally, lightweight, drag or all-rounder) that picks its car, what it buys between races, and sometimes a premium car.'],
        ['🔒', 'Private rooms, simpler', 'If you have the code, you walk straight in. Strangers on the server list ask first, and a private room\'s code is never shown there: the host\'s "yes" sends it, encrypted, to that player only.'],
        ['🔊', 'Sound on by default', 'Engines, tyres and music start with your first click. No more engine or brake sounds left playing in the menus or the garage between rounds.'],
        ['🎨', 'Paint camera', 'In the Paint tab, drag the car to turn it and scroll to zoom.'],
        ['⏳', 'Idle rooms close', 'A lobby that\'s never started closes after 15 minutes, and a room where nobody touches the controls for 10 minutes closes too, with a 2-minute warning.'],
        ['🏁', 'Up to 100 races', 'Sessions can now be 1–100 races long. Prize purses stop growing at 3× so late races don\'t dwarf early ones.'],
      ],
    },
    {
      v: '4.3', name: 'Open Rooms', items: [
        ['🌐', 'Server list', 'Find rooms from any classroom without passing codes around: Menu → 🌐 Server list. Hosts name their room and pick 🔒 Private (you let each new driver in) or 🌐 Public (anyone walks in), plus max drivers and bots, and can change them mid-session from the Esc menu.'],
        ['👑', 'Host migration', 'If the host drops out (or leaves), the next driver who joined takes over and everyone reconnects automatically with their car and money. A host whose internet came back rejoins in their own seat. The old autosave is gone, so nothing is stored between visits.'],
        ['🕐', 'Join any time', 'Late joiners watch the race in progress and drive from the next one, starting with 80% of the poorest driver\'s worth: enough to catch up, never enough to start ahead.'],
        ['💬', 'Chat everywhere', 'Press T or Enter on any screen, even mid-race, to chat. New lines fade in the corner, and the 💬 button counts what you missed.'],
        ['⚖', 'Balance pass', 'New traction control (Tuning → Assists, on by default): keyboard players on rear-drive cars no longer spin away 5 s off the line. Every car now wins somewhere and none wins more than a quarter of the tracks. Apex MR 140 kW and $3,800; Sting weaker on dirt and wet; Brick is the rally car; Dune toned down; tyres weaker and pricier; wings stronger; Big Turbo cheaper; brakes lose less bite when cold.'],
        ['🔧', 'Fixes', 'Test drives end when the next round starts. Name tags stay on cars over hills. Bots no longer swerve for speed pads on drag strips.'],
      ],
    },
    {
      v: '4.2', name: 'Smooth Starts', items: [
        ['🏁', 'First-race desync fixed', 'A slower device (usually a Chromebook on its first race) could freeze for a moment. Its car then carried on with the last keys pressed, straight into a wall, and everyone else\'s car jumped back if the host froze. Now the host catches up after a short freeze instead of losing time, and a bot keeps a frozen player\'s car on the road (at reduced power) until they\'re back.'],
        ['⏳', 'Everyone starts together', 'The countdown waits, up to 8 seconds, until every racer has finished loading the track. The start lights say WAITING meanwhile.'],
        ['🌙', 'Background tabs', 'A game left running in a background tab on a slow device no longer builds up a queue that held back its network messages.'],
      ],
    },
    {
      v: '4.1', name: 'School Wi-Fi', items: [
        ['🛰', 'Backup relay', 'Joining now works when two devices can\'t link directly, such as two Chromebooks on a school Wi-Fi that keeps devices apart. After about 8 seconds without a direct link, the game falls back to a relay through public servers on normal web ports. A message tells you when you\'re on it; expect a little more lag than a direct link.'],
        ['🌐', 'Rooms without matchmaking', 'If the matchmaking server is blocked, a room still opens on the relay, and joiners find it there.'],
        ['💬', 'Clearer join errors', 'A failed join now says which route was blocked and what to try next.'],
      ],
    },
    {
      v: '4.0', name: 'Slipstream & Chaos', items: [
        ['🌬', 'Slipstream', 'Tuck in behind another car to cut your drag by up to 45%: close up, pull out, slingshot past. A SLIPSTREAM meter and wind streaks show when you\'re in the tow.'],
        ['📈', 'Catch-up', 'Cars trailing the leader get extra power: Mild (up to +10%), Wild (up to +25%) or Off for pure racing. The host picks it in the lobby; quick races use your own setting.'],
        ['⚡', 'Nitrous', 'A new performance part: Street Shot (+30%) or Race Shot (+60%). Hold Shift (X or LB on a gamepad, N2O on touch). Drafting another car refills the bottle.'],
        ['🏔', '4 new maps', 'Summit Pass (a real mountain climb with icy hairpins and fallen rocks) · Coastal Highway (a 3 km sprint) · Scrapyard Gauntlet (oil, mud, barrel stacks and boost pads) · Backstretch Mile (a mile-long drag with speed pads in the lanes).'],
        ['🚙', '2 new cars', 'Dune Runner, an AWD desert truck ($2,600), and Apex MR, a mid-engine supercar ($4,800). Premium: buy one once and it\'s yours for the session.'],
        ['🎨', 'More customisation', 'Paint finishes (gloss, metallic, chrome flake, matte), headlight colours, and Fade and Flames liveries.'],
        ['🎲', 'Betting in the flow', 'Racers can back themselves, a bounty sits on the money leader\'s head, and you can go double-or-nothing on your prize after every race. You can back yourself before a quick race too.'],
        ['🗺', 'Hills & hazards', 'Tracks can now climb and dip, and gravity matters. Oil, mud, ice, speed pads and solid obstacles. Bots draft, use nitrous and dodge traps.'],
        ['🔊', 'Sound follows your mods', 'Exhaust changes the whole note (muffled / throaty with a drone / raw straight pipe), a race map crackles and bounces off the limiter, stripped cars are louder inside, sequential boxes whine, wings roar, race brakes squeal. Other cars too — and the garage has a 🔊 Listen button.'],
        ['⚖', 'Balance', 'Sprints get proper run-off after the flag and finished cars take no more damage. Drag grace scales with length. Bots got traction control and stop rear-ending each other. The Scrapyard is 2 laps.'],
      ],
    },
    {
      v: '3.2', name: 'Polish', items: [
        ['🔧', 'Car models', 'No more flickering layers; hood parts, calipers and roundels sit where they should.'],
        ['🧭', 'Minimap', 'The arrows point the way each car is facing.'],
        ['🌐', 'Joining', 'If a join stalls, the host calls the joiner back.'],
        ['🧼', 'Fresh sessions', 'Nothing is saved between visits.'],
      ],
    },
  ];
  // The "What's new" modal body (menu + pause menu).
  G.newsHtml = function (n) {
    return G.CHANGELOG.slice(0, n || 2)
      .map((c, k) => `<div class="news ${k ? 'old' : ''}"><h3>v${c.v} — ${c.name}</h3>${c.items.map(([ic, t, d]) => `<div class="news-i"><span>${G.Icon ? G.Icon.fromEmoji(ic) : ic}</span><div><b>${t}</b><p>${d}</p></div></div>`).join('')}</div>`)
      .join('');
  };
})(window.G);
